# Generated by Django 4.2.16 on 2026-05-30 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Job role / title", max_length=255),
                ),
                ("description", models.TextField(help_text="Detailed job description")),
                (
                    "required_skills",
                    models.TextField(
                        help_text="Comma-separated list of required skills"
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum years of experience required"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("screening", "Screening in progress"),
                            ("pending_approval", "Pending HR approval"),
                            ("approved", "Approved & emails sent"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "langgraph_thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Thread ID used by LangGraph for checkpoint resumption",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "match_score",
                    models.FloatField(
                        default=0.0, help_text="AI-assigned match score (0-100)"
                    ),
                ),
                (
                    "matched_skills",
                    models.TextField(
                        blank=True, help_text="Skills that matched the job requirements"
                    ),
                ),
                (
                    "interview_slot",
                    models.CharField(
                        blank=True,
                        help_text="Assigned interview time slot",
                        max_length=255,
                    ),
                ),
                (
                    "drafted_email",
                    models.TextField(
                        blank=True, help_text="AI-drafted personalized email"
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "resume_source",
                    models.CharField(
                        blank=True,
                        help_text="Original filename of the resume",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("shortlisted", "Shortlisted"),
                            ("email_drafted", "Email Drafted"),
                            ("email_sent", "Email Sent"),
                            ("rejected", "Rejected"),
                        ],
                        default="shortlisted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="core.jobposting",
                    ),
                ),
            ],
            options={
                "ordering": ["-match_score"],
            },
        ),
    ]
