# Generated by Django 4.2.16 on 2026-05-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_companypolicy_faq_employeeprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_period",
                    models.CharField(help_text="e.g., Q1 2026", max_length=100),
                ),
                ("kpi_data", models.TextField(help_text="Raw KPI data or metrics")),
                (
                    "task_completion_rate",
                    models.FloatField(
                        help_text="Percentage of tasks completed (0-100)"
                    ),
                ),
                (
                    "manager_feedback",
                    models.TextField(help_text="Qualitative feedback from the manager"),
                ),
                (
                    "performance_score",
                    models.IntegerField(
                        blank=True, help_text="AI calculated score (0-100)", null=True
                    ),
                ),
                ("kpi_achievement_percent", models.FloatField(blank=True, null=True)),
                ("strengths", models.TextField(blank=True, null=True)),
                ("areas_for_improvement", models.TextField(blank=True, null=True)),
                ("recommended_actions", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="core.employeeprofile",
                    ),
                ),
            ],
        ),
    ]
