# Generated by Django 4.2.16 on 2026-06-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_performancerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Hardware-level employee identifier (e.g. EMP-8472)",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Exact time of the tap event"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        default="rfid_scanner",
                        help_text="Type of hardware device (rfid_scanner, nfc_reader, biometric, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="Main Entrance",
                        help_text="Physical location of the device",
                        max_length=255,
                    ),
                ),
                (
                    "tap_type",
                    models.CharField(
                        choices=[("IN", "Check-In"), ("OUT", "Check-Out")],
                        help_text="Whether this tap was a Check-In or Check-Out",
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Attendance Log",
                "verbose_name_plural": "Attendance Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
